sudo: required
services:
  - docker

before_install:
  - docker build -t pi3ni0/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pi3ni0/react-test npm test

after_success:
  - docker build -t pi3ni0/multi-client ./client
  - docker build -t pi3ni0/multi-nginx ./nginx
  - docker build -t pi3ni0/multi-server ./server
  - docker build -t pi3ni0/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push pi3ni0/multi-client
  - docker push pi3ni0/multi-nginx
  - docker push pi3ni0/multi-server
  - docker push pi3ni0/multi-worker
